<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>slam_project</name>
  <version>0.0.0</version>
  <description>Checkpoint 1, Setting up a c++ node for motion update</description>
  <maintainer email="siddheshsp0@gmail.com">Siddhesh Phadke</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>

    <!-- Added by Siddhesh -->
    <depend>rclcpp</depend>
    <depend>sensor_msgs</depend>
    <depend>visualization_msgs</depend>
    <depend>tf2</depend>
    <depend>tf2_geometry_msgs</depend>
    <exec_depend>eufs_msgs</exec_depend>
    <exec_depend>cuda-toolkit</exec_depend>
    <build_depend>eigen3_cmake_module</build_depend>
    <exec_depend>eigen3_cmake_module</exec_depend>
    <exec_depend>dv_msgs</exec_depend>


    <!-- END -->
    
  </export>
</package>
